In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,21,size = 15)

arr = arr.reshape(3,5)

print(arr.shape)

for i in range(arr.shape[0]):
    max_index = np.argmax(arr[i])
    arr[i, max_index] = 0

arr

(3, 5)


array([[14,  2, 12, 14,  0],
       [ 9, 12,  0,  6,  7],
       [ 4,  0, 10,  6,  1]])

In [4]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]], dtype=np.int32)

print("Shape:", arr.shape)
print("Type:", type(arr))
print("Data type:", arr.dtype)

print("Array data:\n", arr)

Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32
Array data:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
A = np.array([[3, -2],
              [1,  0]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)

[2. 1.]
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [7]:
arr = np.array([[0, 1, 2],
                [3, 4, 5]])
diag_sum = np.trace(arr)

print(diag_sum)

4


In [8]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

print(arr)
# Reshape to 2x3
reshaped_arr = arr.reshape(2, 3)

print("\nReshaped array (2x3):")
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
